export {default as Blog} from './blog/blog';
export {default as Blog2} from './blog2/blog2';
export {default as Features} from './features/features';
export {default as Header} from './header/header';
export {default as Footer} from './footer/footer';
export {default as Possibility} from './possibility/possibility';
export {default as What} from './what/what';
export {default as Ourdoctors} from './ourdoctors/ourdoctors';
export {default as Admin} from './admin/admin';
export {default as ContactUs} from './contactus/contactus';
export {default as Zoom} from './zoom/zoom'
